# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Nazwa firmy')),
            ],
            options={
                'verbose_name': 'Zg\u0142oszenie',
                'verbose_name_plural': 'Zg\u0142oszenia',
            },
        ),
    ]
