# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='category',
            field=models.CharField(choices=[('1', 'Kategoria I'), ('2', 'Kategoria II')], default=None, max_length=255, verbose_name='Kategoria konkursowa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='company_address',
            field=models.TextField(default='', verbose_name='Adres firmy'),
        ),
        migrations.AddField(
            model_name='registration',
            name='description_1',
            field=models.TextField(default='', verbose_name='Kr\xf3tki opis budowy'),
        ),
        migrations.AddField(
            model_name='registration',
            name='description_2',
            field=models.TextField(default='', verbose_name='Zastosowane rozwi\u0105zania'),
        ),
        migrations.AddField(
            model_name='registration',
            name='description_3',
            field=models.TextField(default='', help_text='Rozwi\u0105zania, kt\xf3re wyr\xf3\u017cniaj\u0105 projekt np nietypowe pomieszczenie, kr\xf3tki czas realizacji przy skomplikowanych rozwi\u0105zaniach, d\u017awi\u0119ko-ch\u0142onno\u015b\u0107, zabezpieczenia, nietypowe rozwi\u0105zania ppo\u017c.', verbose_name='Zastosowane systemy Rigips'),
        ),
        migrations.AddField(
            model_name='registration',
            name='email',
            field=models.EmailField(default=None, max_length=255, verbose_name='E-mail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='fax',
            field=models.CharField(default=None, max_length=255, verbose_name='Faks'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='name',
            field=models.CharField(default=None, max_length=255, verbose_name='Imi\u0119 i nazwisko'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='phone',
            field=models.CharField(default=None, max_length=255, verbose_name='Telefon'),
            preserve_default=False,
        ),
    ]
