# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import website.models.registration


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_registration_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('file', models.FileField(upload_to=website.models.registration.upload_path_handler, verbose_name='Za\u0142acznik')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Registration')),
            ],
        ),
    ]
