# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import website.models.configuration


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_registrationfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_file', models.FileField(blank=True, null=True, upload_to=website.models.configuration.upload_path_handler)),
            ],
            options={
                'verbose_name': 'Konfiguracja',
            },
        ),
    ]
