# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields
import website.models.registration


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20170619_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='allow_scan',
            field=models.ImageField(blank=True, null=True, upload_to=website.models.registration.upload_path_handler, verbose_name='Skan zgody'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'P\u0142yty gipsowo-kartonowe'), ('2', 'Rozwi\u0105zania innowacyjne i nienaruszaj\u0105ce r\xf3wnowagi \u015brodowiskowej'), ('3', 'Budynki mieszkalne'), ('4', 'Rozwi\u0105zania sektorowe'), ('5', 'Sufity')], max_length=255, verbose_name='Kategoria konkursowa'),
        ),
    ]
