# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import website.models.configuration


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20170621_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='condition_file',
            field=models.FileField(blank=True, null=True, upload_to=website.models.configuration.upload_path_handler, verbose_name='Plik zformularzem zgody na wykorzystanie zdj\u0119\u0107'),
        ),
    ]
